// flow-typed signature: de16a72fafab7cf6c62875b973d074df
// flow-typed version: <<STUB>>/highcharts_v^4.2.6/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highcharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'highcharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highcharts/adapters/standalone-framework' {
  declare module.exports: any;
}

declare module 'highcharts/adapters/standalone-framework.src' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-3d' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-3d.src' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-more' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts-more.src' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts' {
  declare module.exports: any;
}

declare module 'highcharts/highcharts.src' {
  declare module.exports: any;
}

declare module 'highcharts/highmaps' {
  declare module.exports: any;
}

declare module 'highcharts/highmaps.src' {
  declare module.exports: any;
}

declare module 'highcharts/highstock' {
  declare module.exports: any;
}

declare module 'highcharts/highstock.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/boost' {
  declare module.exports: any;
}

declare module 'highcharts/modules/boost.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/broken-axis' {
  declare module.exports: any;
}

declare module 'highcharts/modules/broken-axis.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/canvas-tools' {
  declare module.exports: any;
}

declare module 'highcharts/modules/canvas-tools.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/data' {
  declare module.exports: any;
}

declare module 'highcharts/modules/data.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/drilldown' {
  declare module.exports: any;
}

declare module 'highcharts/modules/drilldown.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/exporting' {
  declare module.exports: any;
}

declare module 'highcharts/modules/exporting.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/funnel' {
  declare module.exports: any;
}

declare module 'highcharts/modules/funnel.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/heatmap' {
  declare module.exports: any;
}

declare module 'highcharts/modules/heatmap.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/map' {
  declare module.exports: any;
}

declare module 'highcharts/modules/map.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/no-data-to-display' {
  declare module.exports: any;
}

declare module 'highcharts/modules/no-data-to-display.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/offline-exporting' {
  declare module.exports: any;
}

declare module 'highcharts/modules/offline-exporting.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/series-label' {
  declare module.exports: any;
}

declare module 'highcharts/modules/series-label.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/solid-gauge' {
  declare module.exports: any;
}

declare module 'highcharts/modules/solid-gauge.src' {
  declare module.exports: any;
}

declare module 'highcharts/modules/treemap' {
  declare module.exports: any;
}

declare module 'highcharts/modules/treemap.src' {
  declare module.exports: any;
}

declare module 'highcharts/themes/dark-blue' {
  declare module.exports: any;
}

declare module 'highcharts/themes/dark-green' {
  declare module.exports: any;
}

declare module 'highcharts/themes/dark-unica' {
  declare module.exports: any;
}

declare module 'highcharts/themes/gray' {
  declare module.exports: any;
}

declare module 'highcharts/themes/grid-light' {
  declare module.exports: any;
}

declare module 'highcharts/themes/grid' {
  declare module.exports: any;
}

declare module 'highcharts/themes/sand-signika' {
  declare module.exports: any;
}

declare module 'highcharts/themes/skies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highcharts/adapters/standalone-framework.js' {
  declare module.exports: $Exports<'highcharts/adapters/standalone-framework'>;
}
declare module 'highcharts/adapters/standalone-framework.src.js' {
  declare module.exports: $Exports<'highcharts/adapters/standalone-framework.src'>;
}
declare module 'highcharts/highcharts-3d.js' {
  declare module.exports: $Exports<'highcharts/highcharts-3d'>;
}
declare module 'highcharts/highcharts-3d.src.js' {
  declare module.exports: $Exports<'highcharts/highcharts-3d.src'>;
}
declare module 'highcharts/highcharts-more.js' {
  declare module.exports: $Exports<'highcharts/highcharts-more'>;
}
declare module 'highcharts/highcharts-more.src.js' {
  declare module.exports: $Exports<'highcharts/highcharts-more.src'>;
}
declare module 'highcharts/highcharts.js' {
  declare module.exports: $Exports<'highcharts/highcharts'>;
}
declare module 'highcharts/highcharts.src.js' {
  declare module.exports: $Exports<'highcharts/highcharts.src'>;
}
declare module 'highcharts/highmaps.js' {
  declare module.exports: $Exports<'highcharts/highmaps'>;
}
declare module 'highcharts/highmaps.src.js' {
  declare module.exports: $Exports<'highcharts/highmaps.src'>;
}
declare module 'highcharts/highstock.js' {
  declare module.exports: $Exports<'highcharts/highstock'>;
}
declare module 'highcharts/highstock.src.js' {
  declare module.exports: $Exports<'highcharts/highstock.src'>;
}
declare module 'highcharts/modules/boost.js' {
  declare module.exports: $Exports<'highcharts/modules/boost'>;
}
declare module 'highcharts/modules/boost.src.js' {
  declare module.exports: $Exports<'highcharts/modules/boost.src'>;
}
declare module 'highcharts/modules/broken-axis.js' {
  declare module.exports: $Exports<'highcharts/modules/broken-axis'>;
}
declare module 'highcharts/modules/broken-axis.src.js' {
  declare module.exports: $Exports<'highcharts/modules/broken-axis.src'>;
}
declare module 'highcharts/modules/canvas-tools.js' {
  declare module.exports: $Exports<'highcharts/modules/canvas-tools'>;
}
declare module 'highcharts/modules/canvas-tools.src.js' {
  declare module.exports: $Exports<'highcharts/modules/canvas-tools.src'>;
}
declare module 'highcharts/modules/data.js' {
  declare module.exports: $Exports<'highcharts/modules/data'>;
}
declare module 'highcharts/modules/data.src.js' {
  declare module.exports: $Exports<'highcharts/modules/data.src'>;
}
declare module 'highcharts/modules/drilldown.js' {
  declare module.exports: $Exports<'highcharts/modules/drilldown'>;
}
declare module 'highcharts/modules/drilldown.src.js' {
  declare module.exports: $Exports<'highcharts/modules/drilldown.src'>;
}
declare module 'highcharts/modules/exporting.js' {
  declare module.exports: $Exports<'highcharts/modules/exporting'>;
}
declare module 'highcharts/modules/exporting.src.js' {
  declare module.exports: $Exports<'highcharts/modules/exporting.src'>;
}
declare module 'highcharts/modules/funnel.js' {
  declare module.exports: $Exports<'highcharts/modules/funnel'>;
}
declare module 'highcharts/modules/funnel.src.js' {
  declare module.exports: $Exports<'highcharts/modules/funnel.src'>;
}
declare module 'highcharts/modules/heatmap.js' {
  declare module.exports: $Exports<'highcharts/modules/heatmap'>;
}
declare module 'highcharts/modules/heatmap.src.js' {
  declare module.exports: $Exports<'highcharts/modules/heatmap.src'>;
}
declare module 'highcharts/modules/map.js' {
  declare module.exports: $Exports<'highcharts/modules/map'>;
}
declare module 'highcharts/modules/map.src.js' {
  declare module.exports: $Exports<'highcharts/modules/map.src'>;
}
declare module 'highcharts/modules/no-data-to-display.js' {
  declare module.exports: $Exports<'highcharts/modules/no-data-to-display'>;
}
declare module 'highcharts/modules/no-data-to-display.src.js' {
  declare module.exports: $Exports<'highcharts/modules/no-data-to-display.src'>;
}
declare module 'highcharts/modules/offline-exporting.js' {
  declare module.exports: $Exports<'highcharts/modules/offline-exporting'>;
}
declare module 'highcharts/modules/offline-exporting.src.js' {
  declare module.exports: $Exports<'highcharts/modules/offline-exporting.src'>;
}
declare module 'highcharts/modules/series-label.js' {
  declare module.exports: $Exports<'highcharts/modules/series-label'>;
}
declare module 'highcharts/modules/series-label.src.js' {
  declare module.exports: $Exports<'highcharts/modules/series-label.src'>;
}
declare module 'highcharts/modules/solid-gauge.js' {
  declare module.exports: $Exports<'highcharts/modules/solid-gauge'>;
}
declare module 'highcharts/modules/solid-gauge.src.js' {
  declare module.exports: $Exports<'highcharts/modules/solid-gauge.src'>;
}
declare module 'highcharts/modules/treemap.js' {
  declare module.exports: $Exports<'highcharts/modules/treemap'>;
}
declare module 'highcharts/modules/treemap.src.js' {
  declare module.exports: $Exports<'highcharts/modules/treemap.src'>;
}
declare module 'highcharts/themes/dark-blue.js' {
  declare module.exports: $Exports<'highcharts/themes/dark-blue'>;
}
declare module 'highcharts/themes/dark-green.js' {
  declare module.exports: $Exports<'highcharts/themes/dark-green'>;
}
declare module 'highcharts/themes/dark-unica.js' {
  declare module.exports: $Exports<'highcharts/themes/dark-unica'>;
}
declare module 'highcharts/themes/gray.js' {
  declare module.exports: $Exports<'highcharts/themes/gray'>;
}
declare module 'highcharts/themes/grid-light.js' {
  declare module.exports: $Exports<'highcharts/themes/grid-light'>;
}
declare module 'highcharts/themes/grid.js' {
  declare module.exports: $Exports<'highcharts/themes/grid'>;
}
declare module 'highcharts/themes/sand-signika.js' {
  declare module.exports: $Exports<'highcharts/themes/sand-signika'>;
}
declare module 'highcharts/themes/skies.js' {
  declare module.exports: $Exports<'highcharts/themes/skies'>;
}
