// flow-typed signature: c4d11163da69c9e41905160257127e2c
// flow-typed version: <<STUB>>/highcharts-exporting_v^0.1.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highcharts-exporting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'highcharts-exporting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highcharts-exporting/exporting' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highcharts-exporting/exporting.js' {
  declare module.exports: $Exports<'highcharts-exporting/exporting'>;
}
