// flow-typed signature: 98ce99e62d53ad8ab7fe208974a99720
// flow-typed version: <<STUB>>/highcharts-more_v^0.1.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highcharts-more'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'highcharts-more' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highcharts-more/more' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highcharts-more/more.js' {
  declare module.exports: $Exports<'highcharts-more/more'>;
}
